stages:
  split:
    cmd: python src/data_split.py
    deps:
      - data/raw
      - src/data_split.py
    outs:
      - data/split_data

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/split_data
      - src/preprocess.py
    outs:
      - data/processed_images

  train:
    cmd: python src/train.py
    deps:
      - data/processed_images
      - src/train.py
    outs:
      - models/model.h5
    metrics:
      - metrics.json:
          cache: false
